### ISSUE TITLE
which activity groups sum to 1440?

### ISSUE THREAD

**Issue by sarahflood** [roseamw/ATUSGenderSequenceAnalysis#6]
@jrpepin: do you remember exactly which of the activity groups in sequences_1_measures_v1.do sum to 1440? I'd like to build in a test in 02_code_activities.txt to make sure that these parts sum to 1440.

**Comment by jrpepin** [comment]
I cheated a bit which is why you don't see a check for the 1440 sum. I created our activities of interest and anything left over went in an "other" activity category. The primary activity groups are: selfcare; eating; workedu; dailycare; devlpcare; dailyhswk; elsehswk; tele; passnotv; actleis; socleis; shop;

Creating the "other" variable shows up as "dother" on lines 848 -873 in the sequences_1_measures_v1.do file.

**Comment by sarahflood** [comment]
Got it. Thanks!
